
[[news]]
date = "2026-03"
content = "My paper on metabolomic pattern of ultra-processed food and colorectal cancer precursors is online at Gastroenterology!"

[[news]]
date = "2026-02"
content = "My abstract was accepted for an oral presentation at the American Association for Cancer Research (AACR) Annual Meeting 2026, and I was honored to receive the AACR-Jim Wittliff Scholar-in-Training Award!"

[[news]]
date = "2026-02"
content = "My two abstracts were accepted for oral presentations at the Digestive Disease Week (DDW) 2026!"

[[news]]
date = "2026-02"
content = "I’m excited to share that I will be joining the PhD program in Population Health Sciences (Epidemiology) at Harvard starting in Fall 2026! I’m truly grateful for the support and mentorship I’ve received along the way, and I look forward to continuing my work with inspiring mentors and colleagues!"
