[[news]]
date = "2026-04"
content = "Received the Scholar-in-Training Award from the American Association of Cancer Research (AACR)."

[[news]]
date = "2026-01"
content = "Paper on metabolomic pattern of ultra-processed food and colorectal cancer precursors accepted at *Gastroenterology*."

[[news]]
date = "2025-10"
content = "Received the Reviewer's Choice Award at the American Society of Human Genetics (ASHG) Annual Meeting."

[[news]]
date = "2025-05"
content = "Received the Student Abstract Award from the American Gastroenterological Association (AGA)."

[[news]]
date = "2025-03"
content = "Received the Brian MacMahon Travel Award from Harvard T.H. Chan School of Public Health."
