type = "card"
title = "Presentations"
description = ""

[[items]]
title = "Germline genetic impact on risk of colorectal cancer according to birth cohort"
subtitle = "American Association for Cancer Research Annual Meeting — San Diego, US"
date = "2026"
tags = ["Oral", "First Author"]
link = "https://aacrjournals.org/cancerres/article/86/7_Supplement/6816/777890/Abstract-6816-Germline-genetic-impact-on-risk-of"

[[items]]
title = "Germline genetic impact on risk of colorectal cancer according to birth cohort"
subtitle = "Digestive Disease Week — Chicago, US"
date = "2026"
tags = ["Oral", "First Author", "In the News"]
link = "https://news.gastro.org/issues/2026/may-2026/genetic-risk-for-colorectal-cancer-growing-analysis-shows/"

[[items]]
title = "Epidemiological stability of the human gut microbiome and associated factors"
subtitle = "Digestive Disease Week — Chicago, US"
date = "2026"
tags = ["Oral", "First Author"]
link = "https://www.gastrojournal.org/article/S0016-5085(26)00683-9/abstract?referrer=https%3A%2F%2Fwww.researchgate.net%2F"

[[items]]
title = "Metabolomic signature of ultra-processed food intake and risk of colorectal cancer precursors"
subtitle = "Digestive Disease Week — San Diego, US"
date = "2025"
tags = ["Oral", "First Author", "Best of DDW"]

[[items]]
title = "Clonal hematopoiesis of intermediate potential: a modifiable risk factor for prostate and bladder cancer"
subtitle = "American Society of Human Genetics — Boston, US"
date = "2025"
tags = ["Oral", "First Author", "Lightning Talk"]

[[items]]
title = "Development, validation, and prognostic evaluation of a cirrhosis risk score in Chinese"
subtitle = "The Liver Meeting — Washington DC, US"
date = "2025"
tags = ["Poster", "First Author", "Poster of Distinction"]

[[items]]
title = "Physical activity and bone fracture risk in a cohort of prostate cancer patients: Results from the Health Professionals Follow-up Study"
subtitle = "DF/HCC Celebration of Early Career Investigators in Cancer Research — Boston, US"
date = "2025"
tags = ["Poster", "Co-first Author"]

[[items]]
title = "Effects of bariatric surgery on rapid remission of NAFLD: An exploratory metabolomics and validation study"
subtitle = "IFSO World Congress — Melbourne, Australia"
date = "2024"
tags = ["Oral", "Co-first Author"]
