type = "publication"
title = "Selected Publications"
description = "For a full list, see my [Google Scholar](https://scholar.google.com/citations?user=0FlqNzIAAAAJ&hl=en) profile."
source = "publications.bib"
