type = "card"
title = "Teaching"
description = ""

[[items]]
title = "IID 209: Microbial Communities and the Human Microbiome"
subtitle = "Teaching Fellow"
date = "Spring 2026"
content = "Instructor: Dr. Curtis Huttenhower."
tags = ["Microbiome", "Computational Biology"]
link = "https://beta.my.harvard.edu/course/IID209/2026-Spring/1"

[[items]]
title = "ID 201: Core Principles of Biostatistics and Epidemiology for Public Health"
subtitle = "Biostatistics Teaching Fellow"
date = "Fall 2025"
content = "Instructors: Dr. Heather Mattie & Dr. Murray A. Mittleman."
tags = ["Biostatistics", "Epidemiology", "MPH"]
link = "https://beta.my.harvard.edu/course/ID201/2025-Fall/1"
